user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

gafas_gafas:
    resource: "@GafasBundle/Controller/GafasController.php"
    type:     annotation

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /


gafas:
    resource: "@GafasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout
