<?php

namespace GafasBundle\Repository;

/**
 * CarroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarroRepository extends \Doctrine\ORM\EntityRepository
{
}
