<?php

namespace GafasBundle\Repository;

/**
 * GafasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GafasRepository extends \Doctrine\ORM\EntityRepository
{
}
